rm full_article.txt
rm extract_refs.py
rm links.txt
rm check_links.sh
rm link_status.txt
rm improve_article.py
rm fix_refs.py
rm fix_final.py
rm fix_bible.py
rm refine_style.py
rm fix_quotes.py
rm explain_terms.py
rm standardize_citations.py
rm fix_bible_lists.py
rm finalize_layout.py
rm fix_logical_headers.py
rm final_verification.txt
rm final_fixes.py
rm fix_quotes_again.py
